export 'package:dapperz/app_extensions.dart';
export 'package:dapperz/common/app_screen_util.dart';
export 'package:dapperz/common/assets/index.dart';
export 'package:dapperz/common/theme/index.dart';
export 'package:dapperz/controllers/common/app_controller.dart';
export 'package:dapperz/controllers/common/social_login_controller.dart';
export 'package:dapperz/controllers/pages_controller/shop_controller.dart';
export 'package:dapperz/models/index.dart';
export 'package:dapperz/routes/index.dart';
export 'package:dapperz/shimmer_layouts/category_shimmer/category_shimmer.dart';
export 'package:dapperz/shimmer_layouts/shimmer_page_list.dart';
export 'package:dapperz/utilities/app_array.dart';
export 'package:dapperz/utilities/index.dart';
export 'package:dapperz/views/authentication_page/login/login_page_list.dart';
export 'package:dapperz/views/authentication_page/otp/otp_page_list.dart';
export 'package:dapperz/views/authentication_page/sign_up/sign_up_page_list.dart';
export 'package:dapperz/views/bottom_navigate_page/cart/cart_page_list.dart';
export 'package:dapperz/views/bottom_navigate_page/category/category_page_list.dart';
export 'package:dapperz/views/bottom_navigate_page/home/home_page_list.dart';
export 'package:dapperz/views/bottom_navigate_page/inner_category/inner_category_page_list.dart';
export 'package:dapperz/views/checkout/card_balance/card_balance_page_list.dart';
export 'package:dapperz/views/checkout/payment/payment_page_list.dart';
export 'package:dapperz/views/menu/drawer/drawer_layouts/drawer_leading_title.dart';
export 'package:dapperz/views/menu/drawer/drawer_page_list.dart';
export 'package:dapperz/views/menu/drawer/switcher/theme_switcher.dart';
export 'package:dapperz/views/order_page/order_detail/order_detail_page_list.dart';
export 'package:dapperz/views/order_page/order_history/order_history_page_list.dart';
export 'package:dapperz/views/order_page/order_success/order_success_page_list.dart';
export 'package:dapperz/views/pages/about_us/about_us_page_list.dart';
export 'package:dapperz/views/pages/add_address/add_address_page_list.dart';
export 'package:dapperz/views/pages/coupons/coupon_page_list.dart';
export 'package:dapperz/views/pages/delivery_detail/delivery_detail_page_list.dart';
export 'package:dapperz/views/pages/filter/filter_page_list.dart';
export 'package:dapperz/views/pages/help/help_page_list.dart';
export 'package:dapperz/views/pages/page_list/pages_page_list.dart';
export 'package:dapperz/views/pages/product_detail/product_detail_page_list.dart';
export 'package:dapperz/views/pages/profile_setting/profile_page_list.dart';
export 'package:dapperz/views/pages/search/search_page_list.dart';
export 'package:dapperz/views/pages/terms_condition/terms_condition_page_list.dart';
export 'package:dapperz/widgets/common/common_shimmer.dart';
export 'package:flutter/material.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:get/get.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:shimmer/shimmer.dart';

export '../routes/common_screen_list.dart';

class Config {
  static const String razorpayKeyId = 'rzp_test_YOUR_KEY_HERE';
}
